# Generated by Django 4.2.26 on 2026-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohocommerceaccount',
            name='organization_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
