from django.urls import path

from .api_delivery_zones import DeliveryZoneDetailAPIView, DeliveryZoneListCreateAPIView
from .views import (
    UserAddressListCreateAPIView,
    UserAddressDetailAPIView,
    WishlistListCreateAPIView,
    WishlistItemDetailAPIView,
    WishlistMoveToCartAPIView,
    CartDetailAPIView,
    CartSummaryAPIView,
    CartClearAPIView,
    CartAddItemAPIView,
    CheckoutAPIView,
    LoyaltyIssuedCouponListAPIView,
    LoyaltyIssueCouponAPIView,
    RewardPointsAPIView,
    OrderListAPIView,
    OrderDetailAPIView,
    OrderConfirmAPIView,
    OrderZohoBooksInvoiceAPIView,
    OrderZohoBooksPaymentAPIView,
    OrderZohoBooksCancelAPIView,
    OrderCancelAPIView,
    OrderPaymentSuccessAPIView,
    OrderReturnFlowMetaAPIView,
    OrderReturnListCreateAPIView,
    OrderReorderAPIView,
    NotificationListAPIView,
    OfferNotificationListAPIView,
    NotificationUnreadCountAPIView,
    NotificationMarkAllReadAPIView,
    NotificationDetailAPIView,
    RegisterDeviceView,
    UnregisterDeviceView,
    PushSettingsView,
    ZohoProductListAPIView,
    ZohoProductDetailAPIView,
    ZohoProductImageProxyAPIView,
    GeideaInitiateView,
    GeideaCallbackView,
    GeideaStatusView,
    GeideaPollView,
    PayByLinkInitiateView,
)

urlpatterns = [
    path('addresses/', UserAddressListCreateAPIView.as_view(), name='shop-address-list-create'),
    path('addresses/<int:pk>/', UserAddressDetailAPIView.as_view(), name='shop-address-detail'),
    path('wishlist/', WishlistListCreateAPIView.as_view(), name='shop-wishlist-list-create'),
    path('wishlist/item/', WishlistItemDetailAPIView.as_view(), name='shop-wishlist-detail'),
    path('wishlist/move-to-cart/', WishlistMoveToCartAPIView.as_view(), name='shop-wishlist-move-to-cart'),
    path('cart/', CartDetailAPIView.as_view(), name='shop-cart'),
    path('cart/summary/', CartSummaryAPIView.as_view(), name='shop-cart-summary'),
    path('cart/clear/', CartClearAPIView.as_view(), name='shop-cart-clear'),
    path('cart/items/', CartAddItemAPIView.as_view(), name='shop-cart-add-item'),
    path('orders/checkout/', CheckoutAPIView.as_view(), name='shop-checkout'),
    path('rewards/points/', RewardPointsAPIView.as_view(), name='shop-reward-points'),
    path('rewards/coupons/', LoyaltyIssuedCouponListAPIView.as_view(), name='shop-reward-coupons-list'),
    path('rewards/issue-coupon/', LoyaltyIssueCouponAPIView.as_view(), name='shop-reward-issue-coupon'),
    path('orders/return-flow/', OrderReturnFlowMetaAPIView.as_view(), name='shop-order-return-flow'),
    path('orders/returns/', OrderReturnListCreateAPIView.as_view(), name='shop-order-returns-by-query'),
    path('orders/<int:pk>/returns/', OrderReturnListCreateAPIView.as_view(), name='shop-order-returns'),
    path('orders/reorder/', OrderReorderAPIView.as_view(), name='shop-order-reorder-by-query'),
    path('orders/', OrderListAPIView.as_view(), name='shop-order-list'),
    path('orders/confirm/', OrderConfirmAPIView.as_view(), name='shop-order-confirm-by-query'),
    path('orders/detail/', OrderDetailAPIView.as_view(), name='shop-order-detail-by-query'),
    path('orders/<int:pk>/zoho-books/invoice/', OrderZohoBooksInvoiceAPIView.as_view(), name='shop-order-zoho-books-invoice'),
    path('orders/<int:pk>/zoho-books/payment/', OrderZohoBooksPaymentAPIView.as_view(), name='shop-order-zoho-books-payment'),
    path('orders/<int:pk>/zoho-books/cancel/', OrderZohoBooksCancelAPIView.as_view(), name='shop-order-zoho-books-cancel'),
    path('orders/<int:pk>/cancel/', OrderCancelAPIView.as_view(), name='shop-order-cancel'),
    path('orders/<int:pk>/payment-success/', OrderPaymentSuccessAPIView.as_view(), name='shop-order-payment-success'),
    path('orders/zoho-books/invoice/', OrderZohoBooksInvoiceAPIView.as_view(), name='shop-order-zoho-books-invoice-by-query'),
    path('orders/zoho-books/payment/', OrderZohoBooksPaymentAPIView.as_view(), name='shop-order-zoho-books-payment-by-query'),
    path('orders/zoho-books/cancel/', OrderZohoBooksCancelAPIView.as_view(), name='shop-order-zoho-books-cancel-by-query'),
    path('orders/cancel/', OrderCancelAPIView.as_view(), name='shop-order-cancel-by-query'),
    path('orders/payment-success/', OrderPaymentSuccessAPIView.as_view(), name='shop-order-payment-success-by-query'),
    path('orders/<int:pk>/confirm/', OrderConfirmAPIView.as_view(), name='shop-order-confirm'),

    path('notifications/unread-count/', NotificationUnreadCountAPIView.as_view(), name='shop-notifications-unread-count'),
    path('notifications/mark-all-read/', NotificationMarkAllReadAPIView.as_view(), name='shop-notifications-mark-all-read'),
    path('notifications/offers/', OfferNotificationListAPIView.as_view(), name='shop-offer-notifications-list'),
    path('notifications/<int:pk>/', NotificationDetailAPIView.as_view(), name='shop-notification-detail'),
    path('notifications/', NotificationListAPIView.as_view(), name='shop-notifications-list'),
    path('devices/register/', RegisterDeviceView.as_view(), name='shop-device-register'),
    path('devices/unregister/', UnregisterDeviceView.as_view(), name='shop-device-unregister'),
    path('notifications/push-settings/', PushSettingsView.as_view(), name='shop-notifications-push-settings'),

    path('zoho-products/', ZohoProductListAPIView.as_view(), name='zoho-product-list'),
    path('zoho-products/<str:product_id>/', ZohoProductDetailAPIView.as_view(), name='zoho-product-detail'),
    path(
        'zoho-products/<str:product_id>/image/',
        ZohoProductImageProxyAPIView.as_view(),
        name='zoho-product-image-proxy',
    ),
    path('admin/delivery-zones/', DeliveryZoneListCreateAPIView.as_view()),
    path('admin/delivery-zones/<int:pk>/', DeliveryZoneDetailAPIView.as_view()),

    path('geidea/initiate/', GeideaInitiateView.as_view(), name='geidea-initiate'),
    path('geidea/callback/', GeideaCallbackView.as_view(), name='geidea-callback'),
    path('geidea/status/', GeideaStatusView.as_view(), name='geidea-status'),
    path('geidea/poll/', GeideaPollView.as_view(), name='geidea-poll'),
    path('paybylink/initiate/', PayByLinkInitiateView.as_view(), name='paybylink-initiate'),

]
