# Generated by Django 4.2.26 on 2026-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
