# Generated by Django 4.2.25 on 2026-04-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfig',
            name='webhook_type',
            field=models.CharField(choices=[('create_coupon', 'Create Coupon'), ('list_coupons', 'List Coupons'), ('delete_coupon', 'Delete Coupon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='webhookconfig',
            name='webhook_url',
            field=models.TextField(help_text='Full ZAPI key URL from Zoho incoming webhook settings. Includes encapiKey.'),
        ),
    ]
