# Generated by Django 4.2.25 on 2026-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_webhookconfig_webhook_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookconfig',
            name='webhook_type',
            field=models.CharField(choices=[('create_coupon', 'Create Coupon'), ('list_coupons', 'List Coupons'), ('delete_coupon', 'Delete Coupon'), ('get_coupon', 'Get Coupon'), ('update_coupon', 'Update Coupon')], max_length=50),
        ),
    ]
