# Generated by Django 4.2.26 on 2026-06-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLoginOTP',
        ),
    ]
