# Generated by Django 4.2.26 on 2026-04-04 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_zoho', 'Pending Zoho sync'), ('synced', 'Synced to Zoho'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Zoho sync failed')], default='pending_zoho', max_length=32)),
                ('zoho_salesreturn_id', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='zoho_line_item_id',
            field=models.CharField(blank=True, help_text='Zoho sales order line id when synced (for sales returns API).', max_length=120),
        ),
        migrations.CreateModel(
            name='OrderReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_lines', to='shop.orderitem')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='shop.orderreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
