# Generated by Django 4.2.26 on 2026-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('geidea', 'Geidea'), ('credit_debit_card', 'Credit / Debit Card'), ('card_on_delivery', 'Card on Delivery'), ('cash_on_delivery', 'Cash on Delivery'), ('pay_by_link', 'Pay by Link')], default='cash_on_delivery', max_length=32),
        ),
    ]
