# Generated by Django 4.2.25 on 2026-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_order_payment_credit_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cities', models.JSONField(default=list, help_text='List of city/area name strings covered by this zone (case-insensitive match). e.g. ["Dubai", "Deira", "Al Barsha"]. Add as many sub-areas as needed.')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0, help_text='Order subtotal at or above which delivery is free (AED).', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Standard delivery fee when subtotal is below threshold (AED).', max_digits=10)),
                ('cod_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Extra charge added ONLY when payment method is cash_on_delivery (AED).', max_digits=10)),
                ('estimated_delivery_label', models.CharField(blank=True, help_text='Optional label shown to customer, e.g. "Same Day", "1-2 Days".', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
