# Generated by Django 4.2.25 on 2026-06-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_rename_under_processing_to_packed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geidea_merchant_ref',
            field=models.UUIDField(blank=True, help_text='UUID sent to Geidea as merchantReferenceId. Generated on first payment initiation.', null=True),
        ),
    ]
