# Generated by Django 4.2.25 on 2026-06-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_zoho_books_journal_log'),
        ('shop', '0029_order_tracking_stage_history'),
    ]

    operations = [
    ]
