# Generated by Django 4.2.25 on 2026-06-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_loyalty_program_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geidea_refund_id',
            field=models.CharField(blank=True, default='', help_text='Geidea refund transaction ID on cancellation. Non-empty = card refund issued.', max_length=255),
        ),
    ]
