# Generated by Django 4.2.26 on 2026-05-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zoho_category_id',
            field=models.CharField(blank=True, help_text='Zoho Commerce category id when known (from product sync/detail).', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='zoho_collection_id',
            field=models.CharField(blank=True, help_text='Zoho Commerce collection id when present on product payload.', max_length=120),
        ),
    ]
