# Generated by Django 4.2.26 on 2026-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_store_zoho_books_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='zoho_books_org_id',
            field=models.CharField(blank=True, help_text='Zoho Books organization id for invoices (per store). Falls back to ZOHO_BOOKS_ORGANIZATION_ID in .env when empty.', max_length=120),
        ),
    ]
