# Generated by Django 4.2.25 on 2026-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_zoho_books_store_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohobooksstoreconfig',
            name='charge_account_id',
            field=models.CharField(blank=True, help_text='Zoho Books account_id for payment processing charges (expense account).', max_length=120),
        ),
        migrations.AlterField(
            model_name='zohobooksstoreconfig',
            name='deposit_account_id',
            field=models.CharField(blank=True, help_text='Zoho Books account_id for the bank/deposit account. Used as account_id in customerpayments POST body.', max_length=120),
        ),
        migrations.AlterField(
            model_name='zohobooksstoreconfig',
            name='deposit_account_name',
            field=models.CharField(blank=True, help_text='Display label only — for admin reference.', max_length=255),
        ),
        migrations.AlterField(
            model_name='zohobooksstoreconfig',
            name='vat_account_id',
            field=models.CharField(blank=True, help_text='Zoho Books account_id for VAT on payment charges (sub-account of charge_account).', max_length=120),
        ),
    ]
