# Generated by Django 4.2.25 on 2026-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_zohobooksstoreconfig_charge_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='body',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
